[tool.poetry]
name = "blitz_api"
version = "0.5.0"
description = "A backend for the Raspiblitz project"
authors = ["fusion44 <some.fusion@gmail.com>"]
license = "MIT"
packages = [
    { include = "app" },
]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "0.79.0"
fastapi-plugins = "0.9.0"
redis = "4.3.4"
aioredis = "1.3.1"
pydantic = "1.9.1"
uvicorn = "0.18.2"
PyJWT = "2.4.0"
python-decouple = "3.6"
psutil = "5.9.1"
requests = "2.28.1"
pyzmq = "23.2.0"
cchardet = "2.1.7"
aiohttp = "3.8.1"
grpcio = "1.47.0"
grpcio-tools = "1.47.0"
googleapis-common-protos = "1.56.4"
protobuf = "3.20.1"
deepdiff = "5.8.1"
click = "^8.1.3"

[tool.poetry.dev-dependencies]
pytest = "7.1.2"
coverage = "6.4.2"
pyclean = "2.2.0"
pre-commit = "2.20.0"
isort = "5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.poetry.scripts]
api = "app.server:main"
